### ISSUE TITLE
db:schema:load vs rake db:migrate

### ISSUE THREAD

**Issue by edorgeville** [rubocop-hq/rails-style-guide#184]
>  Use `rake db:schema:load` instead of `rake db:migrate` to initialize an empty database.
> https://github.com/bbatsov/rails-style-guide#db-schema-load

Why use one over the other ? Only info I found was going _against_ using db:schema:load as running it on a production server would simply wipe existing database data. (http://stackoverflow.com/a/5905958)

Is it only useful for projects with deleted old migrations ? Is it good practice to delete old migrations you know won't ever be needed again ?

Thanks !

**Comment by espadrine** [comment]
@edorgeville Running it in production would indeed wipe the data, which indeed does what the quote details:

>  to initialize an empty database.

If that is exactly what you want to do, which you sometimes wish to do locally to clean the slate, then db:schema:load will set up the database according to db/schema.rb instead of running all your migrations from db/migrate/, which may include migrations that represent needless work (eg, if a column changed name at some point and was later removed, you don't need to perform the name change, just the removal).

**Comment by pirj** [comment]
> db:schema:load as running it on a production server 

But the guideline says

> to initialize an empty database


> useful for projects with deleted old migrations 

Yes, and also for projects with deleted old models unless the project follows the rule of inlining models, e.g.:
```ruby
  class MigrationUser < ActiveRecord::Base
    self.table_name = 'users'
  end

  def up
    MigrationUser.create!(role: 'admin')
  end
```

And also for projects where due to loaded data some migrations don't apply. E.g. `NOT NULL` on `User`'s `email`.

The current state of the guideline looks ok.
However, if there are some reasonable additions to it - pull request is welcome.

**Comment by sinancengiz** [comment]
So schema:load takes the currently configured schema, derives the associated queries to match, and runs them all in one go. It's kind of a one-and-done situation. As you've seen, migrations make changes step-by-step. Loading the schema might make sense when working on a project locally, especially early in the lifetime of a project. But if we were to drop and recreate the production DB each time we do a deployment, we would lose production data each time. That's a no-go. So that's why we use migrations to make the required changes to the existing DB.

I hope this helps
