### ISSUE TITLE
Never construct raw HTML and use Rails helpers if necessary

### ISSUE THREAD

**Issue by stephwag** [rubocop-hq/rails-style-guide#198]
I noticed that you construct raw HTML in your example here https://github.com/bbatsov/ruby-style-guide#concat-strings

I think you should use a different example and add a section about constructing HTML. In the section, it should explain that you must construct HTML, use helpers such as `content_tag` and avoid writing strings of raw HTML. Not only does this save a bit of time for the programmer, but it also doesn't encourage the use of `html_safe`, which can create an XSS vulnerability if they happen to wrap the html around unclean data.

Original issue https://github.com/bbatsov/ruby-style-guide/issues/594, but this issue concerns Rails so moving it here.

**Comment by andyw8** [comment]
There's another thing to consider here: If you enable `# frozen_string_literal: true` (which might be the default for Ruby 3), then strings cannot be mutated.

**Comment by pirj** [comment]
Just two cents, it seems that freezing by default is not coming as part of Ruby 3, and `+=` is not mutation in-place, so in this sense the example is quite ok. Agree with the original note though.

**Comment by andyw8** [comment]
> and += is not mutation in-place

Yes, but `<<` is mutation, it won't be allowed if `# frozen_string_literal: true` is enabled.

**Comment by pirj** [comment]
Ha, good point. So it's actually the bad example being a good example. 👍 Nice catch.

**Comment by pirj** [comment]
Since this was originally filed, Ruby and Rails guides were separated. The HTML part belongs here, but we don't seem to suggest building HTML using concatenation in the guide. And if the Ruby Style Guide does, it doesn't relate to Rails.

There's surely a problem with suggesting to use `<<` alongside `frozen_string_literal`, but it quickly becomes apparent in practice.

Closing as not actionable.
